fix: revert com.uber.nullaway:nullaway from 0.13.7 to 0.13.8"
This reverts commit 678753204f3889899a8979b71a0e91d2379ef203.

nullaway 0.13.8 produces the following ClassCastException:

java.lang.ClassCastException: class com.sun.tools.javac.code.Type$JCPrimitiveType cannot be cast to class com.sun.tools.javac.code.Type$ArrayType (com.sun.tools.javac.code.Type$JCPrimitiveType and com.sun.tools.javac.code.Type$ArrayType are in module jdk.compiler of loader 'app')
        at com.uber.nullaway.InvocationArguments.<init>(InvocationArguments.java:67)
        at com.uber.nullaway.generics.GenericsChecks.getFormalParameterTypeForArgument(GenericsChecks.java:776)
        at com.uber.nullaway.generics.GenericsChecks.getTargetTypeFromParentContext(GenericsChecks.java:2002)
        at com.uber.nullaway.generics.GenericsChecks.getTargetTypeForConditionalExpression(GenericsChecks.java:1935)
        at com.uber.nullaway.generics.GenericsChecks.checkTypeParameterNullnessForConditionalExpression(GenericsChecks.java:1814)
        at com.uber.nullaway.NullAway.matchConditionalExpression(NullAway.java:1925)
        ...